### ISSUE TITLE
GraphQL Error

### ISSUE THREAD

**Issue by nikhil-xb** [AbdaliDahir/gatsby-portfolio#11]
I am trying to deploy the site using netlify. I have also set the token in netlify, but I am continuously getting this below error
![Screenshot from 2022-11-05 18-15-52](https://user-images.githubusercontent.com/77227336/200120678-73c3fd56-bc16-4530-858b-7fa028394c10.png)

**Comment by kyoyacchi** [comment]
> I am trying to deploy the site using netlify. I have also set the token in netlify, but I am continuously getting this below error ![Screenshot from 2022-11-05 18-15-52](https://user-images.githubusercontent.com/77227336/200120678-73c3fd56-bc16-4530-858b-7fa028394c10.png)

Did you manage to fix it? Can you explain me please? I am trying to use this one too
