### ISSUE TITLE
Github API errors

### ISSUE THREAD

**Issue by jgx0** [AbdaliDahir/gatsby-portfolio#3]
BTW, this is an amazing site you have here. So, I cloned the site, and added my API key. Then I deployed to netlify. I always get this error, no matter what I try. 
![Screenshot_2021-02-13-16_913x388](https://user-images.githubusercontent.com/60720126/107864061-eed9dd00-6e26-11eb-92ab-811b71bfb47e.png)

**Comment by AbdaliDahir** [comment]
hey @orangemn6 

can we start from here

did you added your tokens into netlify environment?
not on .env

smtg  like that
![Screenshot from 2021-02-13 23-47-33](https://user-images.githubusercontent.com/20466978/107864659-59564180-6e56-11eb-9075-92833d7bf71c.png)

**Comment by jgx0** [comment]
![Screenshot_2021-02-14-11_1178x511](https://user-images.githubusercontent.com/60720126/107877408-46fdf700-6e9a-11eb-8901-a93f72c014f4.png)
When I tried this, I got a different error. 
![Screenshot_2021-02-14-22_1192x601](https://user-images.githubusercontent.com/60720126/107877370-0bfbc380-6e9a-11eb-8c7e-75da7122cac3.png)

**Comment by AbdaliDahir** [comment]
can i see what did u selected when u generated the github token??

and if u can try to test it in ur local first just to be sure that the token u have is working well.

ur problem is just with github token

**Comment by jgx0** [comment]
for the token, I selected everything

**Comment by AbdaliDahir** [comment]
> for the token, I selected everything

can u try with this token : and take screenshot for me
12b290453aa318d056f0e57316fc0651a9d4dbd9

**i removed The TOKEN it will not work for u now**

**Comment by jgx0** [comment]
Also the token works for my other apps.
Same thing with that one
![Screenshot_2021-02-14-40_1163x572](https://user-images.githubusercontent.com/60720126/107882605-45432c00-6eb8-11eb-8f48-afe06e36b93d.png)

**Comment by AbdaliDahir** [comment]
ok 

i will check that

**Comment by AbdaliDahir** [comment]
there is no problem with code. for the message u get it's already clear. they can't get data from Github.

it's not query problem or smtg like that.

So, i have now project who is working can u give me ur Token to tested on my local.

i just want to make sure that is not Token error.
![Screenshot from 2021-02-14 18-59-23](https://user-images.githubusercontent.com/20466978/107886325-fe285b80-6ef6-11eb-83d2-813954202a88.png)

**Comment by jgx0** [comment]
ok. My token is `330aa38cb6eae7064c26c798d72ea483def5dc1c`

**Comment by AbdaliDahir** [comment]
ok 

it's working for me as u can see.

i get error on query at first but its different to what u get 

it was related to "name" inside viewer query i removed from query and its work.
that is just because of the different about our repositories  and what we get from it.
![Screenshot from 2021-02-14 19-31-30](https://user-images.githubusercontent.com/20466978/107887181-24042f00-6efc-11eb-8bab-6aa69ce01993.png)

its work here as u can see:
![Screenshot from 2021-02-14 19-32-08](https://user-images.githubusercontent.com/20466978/107887199-46964800-6efc-11eb-8588-be1cde758e82.png)

do u have the same error in ur local?? or u passed directly to deployment

**Comment by jgx0** [comment]
I didn't run it locally, not enough storage to install all the deps. So how can I fix this problem?

**Comment by AbdaliDahir** [comment]
do u have skype 
we need to pass to chat 

add me or contact me via email to see what u have there abdali.dahir@gmail.com

**Comment by AbdaliDahir** [comment]
and because it's not issue related to code 
i will close this. 
u can start to contact me. 
we will try to fix your deployment prblms

**Comment by jgx0** [comment]
k. I got it to work, but only by removing the "name" line

**Comment by jgx0** [comment]
BTW kindof offtopic, but is there an easy CMS/script for making blog posts?

**Comment by jgx0** [comment]
@AbdaliDahir do you use matrix/discord?

**Comment by jgx0** [comment]
Also, I changed the README and now the site gives errors again

**Comment by AbdaliDahir** [comment]
gatsby can be easy i think that u already have idea about how its work.

for CMS maybe wordpress can be good for you but u know u will need domain host smtg like that if u don't want to go with the free version.

and the readme file has no impact to site

can i see your project repository 
i already checked and i can't found it

**Comment by jgx0** [comment]
sure. My repo is [https://github.com/orangemn6/gatsby-portfolio](https://github.com/orangemn6/gatsby-portfolio)

**Comment by AbdaliDahir** [comment]
ok i see it 
don't put ur Token inside ".env.development" and push it to github repo
because github automatically will remove ur token and it will not work again

**Comment by jgx0** [comment]
so delete the line? or just comment it out?

**Comment by AbdaliDahir** [comment]
keep the .env empty and add your tokens to netlify environment 
like i show you on image before

**Comment by jgx0** [comment]
k

**Comment by AbdaliDahir** [comment]
> so delete the line? or just comment it out?

just remove token from .env and generate another one to added to ur netlify environment

**Comment by jgx0** [comment]
ah makes sense

**Comment by AbdaliDahir** [comment]
by the way u can select just "public_repo" and "read:packages" when u try to generate token that all what u need

**Comment by jgx0** [comment]
ok. will try now

**Comment by jgx0** [comment]
YAS it worked!

**Comment by AbdaliDahir** [comment]
Ok that is good

🥳🥳🥳🥳🥳🥳

if u need smtg u welcome at any time

**Comment by jgx0** [comment]
ok. Thank you for the help!

**Comment by AbdaliDahir** [comment]
# 👍

**Comment by jgx0** [comment]
Is there a way for me to add blog posts?

**Comment by AbdaliDahir** [comment]
yeah of course go to src/data/blog
every post is folder
u can start create ur blogs like that "keep the same structure "

the posts are using markdown .md files

same thing with portfolio

**Comment by jgx0** [comment]
ah sick.

**Comment by jgx0** [comment]
Will it work if I have just a file for each post? or do I need  a folder?

**Comment by AbdaliDahir** [comment]
maybe with some customization.  i didn't check that :)
and i don't see a lot of different between both. 
folder will contain also images etc ... to keep things separate maximum.

**Comment by jgx0** [comment]
ok. I will try to look through the code and figure it out
