### ISSUE TITLE
Issue with image rendering

### ISSUE THREAD

**Issue by sid-r-singh** [AbdaliDahir/gatsby-portfolio#4]
1st, let me tell you that this is the best ever 🥇 portfolio gatsby site so far. You guys certainly deserve applause👏  for the awesome work 🥳. 
I just forked your repo & deployed it . I had issues with images getting blurred.
![image](https://user-images.githubusercontent.com/68782815/115321663-ec3a9180-a1a1-11eb-942f-e06fcfab6f2b.png)
![image](https://user-images.githubusercontent.com/68782815/115321738-14c28b80-a1a2-11eb-8e57-f789eaf1f710.png)

**Comment by AbdaliDahir** [comment]
Thnx.
i will try to check that on the weekend
